IF(FFTW_INCLUDE_DIRS)
  FIND_PATH(FFTW_INCLUDE_DIR fftw3.h  ${FFTW_INCLUDE_DIRS})
  FIND_LIBRARY(FFTW_LIBRARY fftw3 ${FFTW_LIBRARY_DIRS})
ELSE(FFTW_INCLUDE_DIRS)
  FIND_PATH(FFTW_INCLUDE_DIR fftw3.h ${APP_INCLUDE_PATHS})
  FIND_LIBRARY(FFTW_LIBRARIES fftw3  ${APP_LIBRARY_PATHS})
ENDIF(FFTW_INCLUDE_DIRS)

IF(FFTW_INCLUDE_DIR)
  SET(FFTW_FOUND 1 CACHE BOOL "Found fftw library")
ELSE(FFTW_INCLUDE_DIR)
  SET(FFTW_FOUND 0 CACHE BOOL "Not Found fftw library")
ENDIF(FFTW_INCLUDE_DIR)

MARK_AS_ADVANCED(
   FFTW_INCLUDE_DIR
   FFTW_LIBRARIES
   FFTW_FOUND
)
